name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  schedule:
    - cron:  '0 4 * * 5' # Fridays at 4am

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --no-lockfile
      - name: Run Tests
        run: pnpm test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          # - ember-lts-4.12
          # - ember-release
          # - ember-beta
          - ember-default-with-jquery
          - ember-classic
          - ember-cp-validations-4
          - ember-cp-validations-5
          - ember-cp-validations-6

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
